### ISSUE TITLE
What is the exact size, i.e., length, with and height of the case

### ISSUE THREAD

**Issue by Orcuslc** [duckythescientist/BinaryKeyboard#4]
Hi, I want to print the case with our school's 3D printing facilities, but it requires the exact size of the case. So I need to know the length, with and height in centimeters/inches. Thanks.

**Comment by duckythescientist** [comment]
The top plate is 38x38x2.4 mm.
The body is 42x42x16 mm.

[case/binary_keyboard.scad](https://github.com/duckythescientist/BinaryKeyboard/blob/master/case/binary_keyboard.scad) has the dimensions.
